<?php

const ASSETS_LEGACYID_ENABLED = true;
const ASSETS_EXPORT_FORMAT = 'A4';
const ASSETS_EXPORT_ORIENTATION = 'portrait';
const ASSETS_AUDIT_INTERVAL = true;
const ASSETS_AUDITINTERVAL_AMOUNT = 1;
const ASSETS_AUDITINTERVAL_UNIT = 'Y';
const ASSETS_AUDIT_DATE = 0;
