<?php

const ASSETS_DIR = '';
const ASSETS_INSTALL_TIME = TIME_NOW;
const ASSETS_LEGACYID_ENABLED = true;

const ASSETS_EXPORT_FORMAT = 'A4';
const ASSETS_EXPORT_ORIENTATION = 'portrait';

const ASSETS_LABEL_HEADER = 'Assets';
const ASSETS_LABEL_LOGO = '';
const ASSETS_LABEL_PER_PAGE = 24;
const ASSETS_LABEL_FORMAT = 'A4';
const ASSETS_LABEL_ORIENTATION = 'portrait';
const ASSETS_LABEL_PAGE_MARGIN_TOP = 0.5;
const ASSETS_LABEL_PAGE_MARGIN_RIGHT = 0.0;
const ASSETS_LABEL_PAGE_MARGIN_BOTTOM = 0.5;
const ASSETS_LABEL_PAGE_MARGIN_LEFT = 0.0;
const ASSETS_LABEL_FONT_SIZE = 0.2;
const ASSETS_LABEL_WIDTH = 5.75;
const ASSETS_LABEL_HEIGHT = 2.5;
const ASSETS_LABEL_PADDING = 0.0;
const ASSETS_LABEL_ROW_GAP = 1.2;
const ASSETS_LABEL_COLUMN_GAP = 1.2;
const ASSETS_LABEL_QR_WIDTH = 100;
const ASSETS_LABEL_QR_HEIGHT = 100;
const ASSETS_LABEL_QR_PADDING_RIGHT = 0.0;
const ASSETS_LABEL_QR_PADDING_TOP = 0.0;
const ASSETS_LABEL_LOGO_HEIGHT = 1.0;
const ASSETS_LABEL_TEXT_PADDING_TOP = 0;
const ASSETS_LABEL_TEXT_PADDING_RIGHT = 0;
const ASSETS_LABEL_TEXT_PADDING_BOTTOM = 0;
const ASSETS_LABEL_TEXT_PADDING_LEFT = 0;
const ASSETS_LABEL_LOGO_MARGIN_TOP = 0.05;
const ASSETS_LABEL_LOGO_MARGIN_RIGHT = 0.05;

const ASSETS_AUDIT_INTERVAL = true;
const ASSETS_AUDITINTERVAL_AMOUNT = 1;
const ASSETS_AUDITINTERVAL_UNIT = 'Y';
const ASSETS_AUDIT_DATE = 0;
